services:
  web:
    build:
      context: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn nginxTest.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./../.env/dev.env
  nginx:
    build:
      context: ./../nginx/
    ports:
      - 8080:80
    volumes:
      - ./../nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles

volumes:
  static_files: