services:
  nginx:
    build:
      context: .
    ports:
      - 8000:80
      # volumes is the volumes in the docker image
      # we will map the /usr/share/nginx/html with curent folder directory folder html
      # toBeMappedDriectory:mapping directory
    volumes:
      - ./html/:/usr/share/nginx/html/